name: Playwright Tests & Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    env:
      # Credenciais do Firebase
        NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
        NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
        # Credenciais da Vercel
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    # Instala o navegador do Playwright
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Roda os testes
    - name: Run Playwright tests
      run: npx playwright test

    # --- FASE DE DEPLOY (Só roda se os testes passaram) ---
    - name: Deploy to Vercel (Production)
      # Só executa se for push na main E se os testes anteriores passaram
      if: github.ref == 'refs/heads/main' && success()
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        npm install --global vercel@latest
        # Puxa configs de ambiente de produção
        vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        # Faz o build usando a nuvem da Vercel
        vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        # Publica os arquivos gerados
        vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
